// CS Network — contenu du site. Ajouter un campus ou un pôle = ajouter une entrée ici.
// published: true  = le campus est en ligne (pages générées, QR codes, navigation)
// published: false = le campus est masqué, affiché « Bientôt » sur l'accueil
window.CSN_DATA = {
  order: ['rennes', 'metz', 'gif'],
  campuses: {
    rennes: { name: 'Rennes', published: true, place: 'Cesson-Sévigné, Bretagne', intro: "Quatre pôles pour faire venir les anciens et les professionnels sur le campus, et pour documenter les parcours des centraliens.", poles: [
      { id: 'conferences', name: 'Conférences', tagline: "Des anciens et des professionnels interviennent sur le campus toute l'année.", desc: "Des anciens et des professionnels interviennent sur le campus toute l'année. Le pôle prend en charge chaque intervention : choix du format, date, public et logistique. Vous avez une expérience à partager ? Proposez un sujet, nous nous occupons du reste.", email: 'conferences.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Maxime [Nom]', photo: '' }] },
      { id: 'podcast', name: 'Podcast', tagline: "Des anciens racontent ce qu'ils font vraiment.", desc: "Des anciens racontent ce qu'ils font vraiment. Chaque épisode revient sur un parcours, un métier et les choix qui l'ont construit. L'enregistrement dure environ une heure, sur le campus ou à distance.", email: 'podcast.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Marius [Nom]', photo: '' }, { name: 'Lili Meï [Nom]', photo: '' }] },
      { id: 'stages', name: 'Stages centraliens', tagline: 'La base des stages réalisés par des centraliens.', desc: "La base des stages réalisés par des centraliens. Le pôle recense missions, entreprises et retours d'expérience pour orienter les promotions suivantes. Les entreprises peuvent y faire connaître leurs offres.", email: 'stages.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Clara [Nom]', photo: '' }] },
      { id: 'associations', name: 'Aide aux associations', tagline: 'Met en relation les assos du campus avec les anciens.', desc: "Met en relation les associations du campus avec les anciens. Mentorat, expertise ponctuelle ou partenariat : le pôle identifie le bon interlocuteur pour chaque projet étudiant.", email: 'assos.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Agathe [Nom]', photo: '' }] }
    ] },
    metz: { name: 'Metz', published: false, place: 'Technopôle, Grand Est', intro: "Un campus tourné vers l'international et l'industrie, où les pôles organisent les rencontres entre étudiants et entreprises de la région.", poles: [
      { id: 'conferences', name: 'Conférences', tagline: "Des tables rondes avec des acteurs de l'industrie et de l'énergie.", desc: "Le pôle organise des tables rondes avec des acteurs de l'industrie, de l'énergie et du transfrontalier. Chaque séance réunit deux ou trois intervenants autour d'un sujet concret, suivie d'un échange avec les étudiants.", email: 'conferences.metz@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Thomas [Nom]', photo: '' }] },
      { id: 'mentorat', name: 'Mentorat', tagline: 'Un ancien accompagne un étudiant pendant une année.', desc: "Un ancien accompagne un étudiant pendant une année scolaire, à raison d'un échange par mois. Le pôle forme les binômes selon le secteur et le projet professionnel de chacun.", email: 'mentorat.metz@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Inès [Nom]', photo: '' }] },
      { id: 'forum', name: 'Forum entreprises', tagline: 'Une journée de rencontres sur le campus chaque automne.', desc: "Chaque automne, le pôle réunit une trentaine d'entreprises sur le campus pour une journée de rencontres. Stands, entretiens courts et présentations métiers : les inscriptions sont ouvertes dès juin.", email: 'forum.metz@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Hugo [Nom]', photo: '' }] },
      { id: 'stages', name: 'Stages centraliens', tagline: 'Les stages des étudiants de Metz, recensés et commentés.', desc: "Le pôle recense les stages réalisés par les étudiants de Metz, en France comme à l'étranger. Les entreprises peuvent y déposer leurs offres et consulter les retours des stagiaires précédents.", email: 'stages.metz@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Camille [Nom]', photo: '' }] }
    ] },
    gif: { name: 'Paris-Saclay', published: false, place: 'Gif-sur-Yvette, Île-de-France', intro: "Le plus grand campus de l'école, au cœur du plateau de Saclay. Cinq pôles relient les étudiants aux anciens et aux entreprises franciliennes.", poles: [
      { id: 'conferences', name: 'Conférences', tagline: "Un cycle mensuel d'interventions d'anciens et de dirigeants.", desc: "Un cycle mensuel d'interventions d'anciens et de dirigeants, dans l'amphithéâtre du bâtiment Eiffel. Le pôle s'occupe du programme, de la communication et de l'accueil des intervenants.", email: 'conferences.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Louis [Nom]', photo: '' }] },
      { id: 'mentorat', name: 'Mentorat', tagline: 'Des binômes ancien-étudiant, formés par secteur.', desc: "Le pôle forme des binômes entre anciens et étudiants, par secteur et par métier. Un engagement léger : quatre à six échanges sur l'année, en présentiel ou en visio.", email: 'mentorat.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Sarah [Nom]', photo: '' }] },
      { id: 'rencontres', name: 'Rencontres alumni', tagline: 'Des soirées sectorielles entre étudiants et anciens.', desc: "Des soirées sectorielles à Paris et sur le campus : conseil, finance, énergie, tech. Les anciens y rencontrent les étudiants dans un format court et informel.", email: 'rencontres.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Yanis [Nom]', photo: '' }, { name: 'Emma [Nom]', photo: '' }] },
      { id: 'stages', name: 'Stages centraliens', tagline: 'La base des stages réalisés par des centraliens.', desc: "La base des stages réalisés par les centraliens du campus. Missions, entreprises et retours d'expérience y sont recensés pour guider les promotions suivantes.", email: 'stages.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Nour [Nom]', photo: '' }] },
      { id: 'podcast', name: 'Podcast', tagline: "Des parcours d'anciens racontés en une heure.", desc: "Chaque mois, un ancien revient sur son parcours et son métier au quotidien. Les épisodes sont enregistrés au studio du campus ou à distance.", email: 'podcast.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Paul [Nom]', photo: '' }] }
    ] }
  }
};
