// CS Network — contenu du site. Ajouter un campus ou un pôle = ajouter une entrée ici.
// published: true  = le campus est en ligne (pages générées, QR codes, navigation)
// published: false = le campus est masqué, affiché « Bientôt » sur l'accueil
window.CSN_DATA = {
  order: ['rennes', 'metz', 'gif'],
  campuses: {
    rennes: { name: 'Rennes', published: true, place: 'Cesson-Sévigné, Bretagne', intro: "Quatre pôles pour faire venir les anciens et les professionnels sur le campus, et pour documenter les parcours des centraliens.", poles: [
      { id: 'conferences', name: 'Conférences', tagline: "Des anciens et des professionnels interviennent sur le campus toute l'année.", desc: "Des anciens et des professionnels interviennent sur le campus toute l'année. Le pôle prend en charge chaque intervention : choix du format, date, public et logistique. Vous avez une expérience à partager ? Proposez un sujet, nous nous occupons du reste.", email: 'conferences.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Maxime [Nom]', photo: '' }] },
      { id: 'podcast', name: 'Podcast', tagline: "Des anciens racontent ce qu'ils font vraiment.", desc: "Des anciens racontent ce qu'ils font vraiment. Chaque épisode revient sur un parcours, un métier et les choix qui l'ont construit. L'enregistrement dure environ une heure, sur le campus ou à distance.", email: 'podcast.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Marius [Nom]', photo: '' }, { name: 'Lili Meï [Nom]', photo: '' }] },
      { id: 'stages', name: 'Stages centraliens', tagline: 'La base des stages réalisés par des centraliens.', desc: "La base des stages réalisés par des centraliens. Le pôle recense missions, entreprises et retours d'expérience pour orienter les promotions suivantes. Les entreprises peuvent y faire connaître leurs offres.", email: 'stages.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Clara [Nom]', photo: '' }] },
      { id: 'associations', name: 'Aide aux associations', tagline: 'Met en relation les assos du campus avec les anciens.', desc: "Met en relation les associations du campus avec les anciens. Mentorat, expertise ponctuelle ou partenariat : le pôle identifie le bon interlocuteur pour chaque projet étudiant.", email: 'assos.rennes@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Agathe [Nom]', photo: '' }] }
    ] },
    metz: { name: 'Metz', published: true, place: 'Technopôle, Grand Est', intro: "L'antenne de Metz se met en place. Les pôles ouvriront dans un second temps : en attendant, l'équipe est joignable directement.", poles: [], team: [
      { name: 'Achille Train-Lagarde', role: 'Président', bureau: true, email: 'achille.train-lagarde@student-cs.fr', linkedin: 'https://www.linkedin.com/in/achilletn/', photo: '' },
      { name: 'Ilyess Amrani', role: 'Vice-Président', bureau: true, email: 'ilyess.amrani@student-cs.fr', linkedin: 'https://www.linkedin.com/in/ilyess-amrani-9a6b5536a/', photo: '' },
      { name: 'Maxime Sastre', role: 'Trésorier', bureau: true, email: 'maxime.sastre@student-cs.fr', linkedin: 'https://www.linkedin.com/in/maxime-sastre/', photo: '' },
      { name: 'Louis Renou', role: 'Secrétaire général', bureau: true, email: 'louis.renou@student-cs.fr', linkedin: 'https://www.linkedin.com/in/louisrenou/', photo: '' },
      { name: 'Adrien Cunha', role: 'Membre', email: 'adrien.cunha@student-cs.fr', linkedin: 'https://www.linkedin.com/in/adrien-cunha/', photo: '' },
      { name: 'Damien Mandon', role: 'Membre', email: 'damien.mandon@student-cs.fr', linkedin: 'https://www.linkedin.com/in/damien-mandon-b93497379/', photo: '' },
      { name: 'Noé Schmied', role: 'Membre', email: 'noe.schmied@student-cs.fr', linkedin: 'https://www.linkedin.com/in/no%C3%A9-schmied-4664183b0/', photo: '' },
      { name: 'Jean-Baptiste De Leusse', role: 'Membre', email: 'jean-baptiste.deleusse@student-cs.fr', linkedin: 'https://www.linkedin.com/in/jean-baptiste-de-leusse-8a8239270/', photo: '' },
      { name: 'Anas Tariq', role: 'Membre', email: 'anas.tariq@student-cs.fr', linkedin: 'https://www.linkedin.com/in/anas-tariq-1b933623a/', photo: '' },
      { name: 'Maxime Chiabodo', role: 'Membre', email: 'maxime.chiabodo@student-cs.fr', linkedin: 'https://www.linkedin.com/in/mchiabodo/', photo: '' },
    ] },
    gif: { name: 'Paris-Saclay', published: false, place: 'Gif-sur-Yvette, Île-de-France', intro: "Le plus grand campus de l'école, au cœur du plateau de Saclay. Cinq pôles relient les étudiants aux anciens et aux entreprises franciliennes.", poles: [
      { id: 'conferences', name: 'Conférences', tagline: "Un cycle mensuel d'interventions d'anciens et de dirigeants.", desc: "Un cycle mensuel d'interventions d'anciens et de dirigeants, dans l'amphithéâtre du bâtiment Eiffel. Le pôle s'occupe du programme, de la communication et de l'accueil des intervenants.", email: 'conferences.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Louis [Nom]', photo: '' }] },
      { id: 'mentorat', name: 'Mentorat', tagline: 'Des binômes ancien-étudiant, formés par secteur.', desc: "Le pôle forme des binômes entre anciens et étudiants, par secteur et par métier. Un engagement léger : quatre à six échanges sur l'année, en présentiel ou en visio.", email: 'mentorat.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Sarah [Nom]', photo: '' }] },
      { id: 'rencontres', name: 'Rencontres alumni', tagline: 'Des soirées sectorielles entre étudiants et anciens.', desc: "Des soirées sectorielles à Paris et sur le campus : conseil, finance, énergie, tech. Les anciens y rencontrent les étudiants dans un format court et informel.", email: 'rencontres.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Yanis [Nom]', photo: '' }, { name: 'Emma [Nom]', photo: '' }] },
      { id: 'stages', name: 'Stages centraliens', tagline: 'La base des stages réalisés par des centraliens.', desc: "La base des stages réalisés par les centraliens du campus. Missions, entreprises et retours d'expérience y sont recensés pour guider les promotions suivantes.", email: 'stages.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Nour [Nom]', photo: '' }] },
      { id: 'podcast', name: 'Podcast', tagline: "Des parcours d'anciens racontés en une heure.", desc: "Chaque mois, un ancien revient sur son parcours et son métier au quotidien. Les épisodes sont enregistrés au studio du campus ou à distance.", email: 'podcast.gif@csnetwork.fr', linkedin: 'https://www.linkedin.com/', leads: [{ name: 'Paul [Nom]', photo: '' }] }
    ] }
  }
};
